### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by daanhb** [JuliaApproximation/DomainSets.jl#101]

**Comment by zsunberg** [comment]
Yes... there are many concepts in this package - it definitely deserves more documentation than is currently in the README.

For instance, rotations apparently exist in the source code, but are not mentioned in the docs.

**Comment by zsunberg** [comment]
If someone sets up the documentation structure with Documenter.jl, I bet people would be happy to add to it incrementally. I may submit a PR for this if I get the chance.

**Comment by daanhb** [comment]
> For instance, rotations apparently exist in the source code, but are not mentioned in the docs.

This one is because I think rotations do not belong in this package :-) The plan is still to remove all functionality involving maps and put it into a separate package that can be developed independently (and possibly merged with one of the many other similar packages).

**Comment by daanhb** [comment]
It's live (but empty for now): https://JuliaApproximation.github.io/DomainSets.jl/dev
