### ISSUE TITLE
Should boundary(::Rectangle) use simpler types?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/DomainSets.jl#142]
I'm wondering if it would be more natural to have a notion of a rectangle embedded in a higher dimensional space rather than representing them as affine mapped rectangles... eg I would have expected the boundary of a 2D rectangle to be a union of `LineSegment`s instead of affine mapped unit intervals.

I guess the two definitions are equivalent so maybe its just a question of making a type alias with prettier printing? That is, we could have `LineSegment(a,b)` create an affine mapped interval.

**Comment by daanhb** [comment]
Sure, we could have an alias. It would be good to have more general faces and edges etcetera, but of course multiple other packages provide that. I'd like to get #141 out of the way so that we can move on, I have some code depending on it in the meantime so I'll merge and fix any issues that arise.

**Comment by daanhb** [comment]
Dup of #100
