### ISSUE TITLE
Allow Makie v0.21

### ISSUE THREAD

**Issue by PhyX-Meow** [JuliaApproximation/DomainSets.jl#166]
Tested locally, all test passed, and the picture looks good.

**Comment by dlfivefifty** [comment]
We'll merge a PR. Probably CompatHelper will make one soon but otherwise if you wish to make a PR please feel free.

**Comment by dlfivefifty** [comment]
Hmm for some reason CompatHelper didn't make a PR so I've made one by hand: https://github.com/JuliaApproximation/DomainSets.jl/pull/167

**Comment by PhyX-Meow** [comment]
That's perhaps because the Makie extension was added after Makie's v0.21 release. Thank you for this!

**Comment by dlfivefifty** [comment]
Oh whoops 😅
