### ISSUE TITLE
Can DomainSets be updated to 0.0.2?

### ISSUE THREAD

**Issue by vincentcp** [JuliaApproximation/DomainSets.jl#39]
I would like to use the new naming conventions that are in master.

**Comment by daanhb** [comment]
Is there anything we should do here other than tagging the new release?

**Comment by dlfivefifty** [comment]
Let me test ApproxFun with master, but tag when you are ready.

**Comment by dlfivefifty** [comment]
Can you tag as `v0.1.0`? It makes it easier to specify version ranges.

**Comment by dlfivefifty** [comment]
Nevermind, I can just do `DomainSets = "^0.0.1"` and that defaults to non-compatibility with `v0.0.2`.

**Comment by dlfivefifty** [comment]
https://julialang.github.io/Pkg.jl/v1/compatibility/

**Comment by dlfivefifty** [comment]
I've updated ApproxFun now so it should be fine to tag a new release

**Comment by vincentcp** [comment]
Release `v0.0.2` is published

**Comment by dlfivefifty** [comment]
Tagging doesn’t publish a new version. Please delete the tag and follow the instructions on Registrator.jl

**Comment by vincentcp** [comment]
Ok, is `Registrator.jl` already installed on `DomainSets.jl`?

**Comment by dlfivefifty** [comment]
Yes its installed on all JuliaApproximation repositories. It will tag automatically when the release is merged.

**Comment by vincentcp** [comment]
@JuliaRegistrator register()

**Comment by dlfivefifty** [comment]
We need to retrigger:

@JuliaRegistrator register()
