### ISSUE TITLE
Split out "isomorphisms"

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/DomainSets.jl#43]
The concept of isomorphisms is useful, but is orthogonal to the concept of domains. The way the package interweaves these two ideas makes the code hard to modify. I'd propose removing all references to isomorphisms from DomainSets.jl and moving them to another package, say ArrayIsomorphisms.jl. (Isomorphisms.jl seems to broad.)

**Comment by daanhb** [comment]
This has been done in #55, the issue can be closed if #55 is ready to be merged.

**Comment by daanhb** [comment]
This has been done in #55, the issue can be closed if #55 is ready to be merged.
