### ISSUE TITLE
Length show output for high-dimensional ProductDomains

### ISSUE THREAD

**Issue by oschulz** [JuliaApproximation/DomainSets.jl#65]
This is currently a bit unwieldy ... :-)

```julia
ProductDomain([0..i for i in 1:500])
```

Should probably use a `...` or so to shorten it, like show for long arrays.

**Comment by daanhb** [comment]
Right :-)
I'll have to look into how to do that. For the time being, I think the semicolon at the end of the line will be your friend (to suppress output).
