### ISSUE TITLE
Support more static arrays

### ISSUE THREAD

**Issue by daanhb** [JuliaApproximation/DomainSets.jl#72]
Right now, a "Euclidean domain" is defined to be:
```julia
const EuclideanDomain{N,T} = Domain{SVector{N,T}}
```

It may be more generic to make this into:
```julia
const EuclideanDomain{N,T} = Domain{<:StaticVector{N,T}}
```
That would support other kinds of static vectors apart from `SVector`.

**Comment by dlfivefifty** [comment]
Actually maybe not: `Domain{<:SphericalCoordinate}` is definitely not Euclidean

**Comment by daanhb** [comment]
Alright let's leave this potential change until it is genuinely needed somewhere else, and then figure out a clean solution.
