### ISSUE TITLE
Annuli?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/DomainSets.jl#74]
Are annuli (in 1D, 2D, 3D) implemented here? Should I add it here or in a different package?

I don't think it can be done as a set difference of two balls since that doesn't contain the fact that the two balls are centred in the same place

**Comment by dlfivefifty** [comment]
er I guess it can because its a set difference of two Linear mapped balls, not affine mapped balls,

**Comment by daanhb** [comment]
I guess it could be done that way, but that does not mean it is the best or most efficient way. It might be a reason for not having it in this package, though it wouldn't bother me. If you want to treat an annulus as an annulus somewhere else, it is probably best to make it its own type.

**Comment by dlfivefifty** [comment]
For now the setdiff version works fine. In terms of efficiency it should be compiled down to be equivalent to a custom type
