### ISSUE TITLE
Implicit pinv of vectors

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaApproximation/DomainSets.jl#82]
Hi,

Investigating https://github.com/JuliaLang/julia/pull/40758 I found out that this package fails under that PR, which undefines number / vector (which makes an implicit pseudo-inverse of the vector). I haven't been able to pinpoint where exactly it fails in this package, but it's something to do with test_generic_map(m). Can you confirm if this use of the pseudo-inverse is intended, or a bug and `number ./ vector` is meant?

**Comment by daanhb** [comment]
I do sympathise with the cause :-)
